### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by Mad-Monty** [eSkiSo/TransmogrifyResize#1]
Getting the following error consistently. Sometimes the window will not resize until reloading UI.

13x ...aceTransmogrifyResize/TransmogrifyResize.lua:18: attempt to index global 'WardrobeFrame' (a nil value)
[string "@TransmogrifyResize/TransmogrifyResize.lua"]:18: in function `ResizeTransmogrify'
[string "@TransmogrifyResize/TransmogrifyResize.lua"]:9: in function <...aceTransmogrifyResize/TransmogrifyResize.lua:6>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals:
frameWidth = 1673.333496
frameHeight = 960
modelSceneWidth = 1011.333496
modelSceneHeight = 849
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WardrobeFrame' (a nil value)"

**Comment by eSkiSo** [comment]
Just pushed an update to check if frame exists before applying the resize (pending Curseforge approval).
I have been using it for a while without any issues, it could be incompatibility with some other addon. 
Are you using something like ElvUI or other UI changing addons?

**Comment by Mad-Monty** [comment]
I am using SUI, which does have its own issues that I've posted to their GitHub. I have tested with and without SUI running and have seen similar things happen so far, so it could be an issue with a completely different addon. I can update if I figure out where its coming from.

**Comment by Mad-Monty** [comment]
Been playing with the update. No more errors! Thank you so much for the quick fix!
